name = "chainpulse"
main = ".output/server/index.mjs"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".output/public", binding = "ASSETS", not_found_handling = "single-page-application" }
observability = { enabled = true }

[vars]
NUXT_NEO4J_DATABASE = "neo4j"
NUXT_NEO4J_USER = "neo4j"

[vars.development]
NUXT_NEO4J_DATABASE = "neo4j"
NUXT_NEO4J_USER = "neo4j"